Repository Dyslexia-Done/online-reading-tutor, pull requests merged in 2020-04, with the labels that each got.

#22 update readme to include lint instructions
  README.md
Labels: documentation

#4 added some game components
  App.js
  package.json
  src/assets/game_menu.png
  src/components/Constants.js
  src/components/Game.js
  src/components/Obstacle.js
  src/components/Physics.js
  src/components/Platform.js
  src/components/Player.js
  src/screens/GameScreen.js
  src/screens/MinigameScreen.js
  yarn.lock
Labels: development

#23 New color palette
  App.js
  src/styles/global.js
  src/styles/variables.js
Labels: design, enhancement

#32 added random obstacles. this closes #28 and closes #31
  src/assets/platform.png
  src/components/Constants.js
  src/components/Game.js
  src/components/Obstacle.js
  src/components/Physics.js
  src/components/Platform.js
  src/screens/MinigameScreen.js
Labels: Priority: MVP, development, minigame
